apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: "$GRAFANA_DATA_SOURCE_NAME"
spec:
  name: middleware.yaml
  datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: "${PROMETHEUS_URL}"
      isDefault: true
      version: 1
      editable: true
      jsonData:
        tlsSkipVerify: true
        timeInterval: "5s"
